## Persistent Volume
persistence:
  enabled: true
  # existingDataClaim:
  storageClass: ""
  dataAccessMode: ReadWriteOnce
  dataSize: 200Gi

image:
  repository: octopusdeploy/octopusdeploy
  tag: 2021.3.8275

statefulset:
  annotations: {}
  labels: {}

secret:
  # existingSecret:
  masterKey: {}
  license: {}

admin:
  username: "admin"
  password: "Password01!"
  email: "admin@example.com"

### Service
service:
  annotations: {}
  labels: {}
  type: LoadBalancer
  ports:
    web: 8080
    tentacle: 10943

## MSSQL
mssql:
  connectionString: "Server=mssql,1433;Database=Octopus;User Id=SA;Password=Password01!"
