## Persistent Volume
persistence:
  enabled: true
  # existingDataClaim:
  storageClass: ""
  dataAccessMode: ReadWriteOnce
  dataSize: 200Gi

image:
  repository: octopusdeploy/octopusdeploy
  tag: 2021.3.8275

statefulset:
  annotations: {}
  labels: {}

secret:
  # existingSecret:
  masterKey: {}
  admin:
    username: "admin"
    password: "admin"
    email: "admin@example.com"

### Service
service:
  annotations: {}
  labels: {}
  type: LoadBalancer
  port: 8080

## MSSQL
mssql:
  sapassword: "Password01!"

  ## Persistent Volume
  persistence:
    dataSize: 50Gi

