## Persistent Volume
persistence:
  enabled: true
  # existingDataClaim:
  storageClass: ""
  dataAccessMode: ReadWriteOnce
  dataSize: 200Gi

image:
  repository: octopusdeploy/octopusdeploy
  tag: 2021.3.8275

statefulset:
  annotations: {}
  labels: {}

secret:
  # existingSecret:
  masterKey: {}
  license: {}

admin:
  username: "admin"
  password: "admin"
  email: "admin@example.com"

### Service
service:
  annotations: {}
  labels: {}
  type: LoadBalancer
  port: 8080

## MSSQL
mssql:
  host: "mssql"
  password: "Password01!"
  port: 1433

