{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "octopus.fullname" . }}-secret
  labels:
    app: {{ template "octopus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.secret.masterKey }}
  masterKey:  {{ .Values.secret.masterKey | b64enc | quote }}
  {{ else }}
  masterKey: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
  {{ if .Values.secret.license }}
  license: {{ .Values.secret.license | b64enc | quote }}
  {{ end }}
{{- end -}}
