{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "octopus.fullname" . }}-secret
  labels:
    app: {{ template "octopus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.secret.masterKey }}
  masterKey:  {{ .Values.secret.masterKey | b64enc | quote }}
  {{ else }}
  masterKey: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
  admin_username:  {{ .Values.secret.admin.username | b64enc | quote }}
  {{ if .Values.secret.admin.password }}
  admin_password:  {{ .Values.secret.admin.password | b64enc | quote }}
  {{ else }}
  admin_password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
  admin_email: {{ .Values.secret.admin.email | b64enc | quote }}

{{- end -}}
