apiVersion: v1
kind: Service
metadata:
  name: {{ template "octopus.name" . }}
  labels:
    app: {{ template "octopus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}    
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
  selector:
    app: {{ template "octopus.name" . }}
    release: {{ .Release.Name }}