edition: Express 
collation: SQL_Latin1_General_CP1_CI_AS
lcid: 1033
hadr: 0
agent:
  enabled: false

# Override sapassword in templates/secret.yaml
# sapassword: "Password01!"
existingSecret: ""
existingSecretKey: sapassword
image:
  repository: mcr.microsoft.com/mssql/server
  tag: 2019-latest  
  pullPolicy: IfNotPresent

## Deployment
deployment:
  annotations: {}
  labels: {}

pod:
  annotations: {}
  labels: {}

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName: "default-scheduler"

### Service
service:
  annotations: {}
  labels: {}
  # If headless is set to TRUE then the service type is ignored
  headless: false
  type: ClusterIP
  port: 1433
  nodePort: 
  loadBalancerIP:

## Persistent Volume
persistence:
  enabled: true
  # existingDataClaim:
  # existingTransactionLogClaim:
  # existingBackupClaim:
  # existingMasterClaim:
  storageClass: ""
  dataAccessMode: ReadWriteOnce
  dataSize: 8Gi

livenessprobe:
  initialDelaySeconds: 15
  periodSeconds: 20
readinessprobe:
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  limits: {}
  #  cpu: 100m
  #  memory: 2Gi
  # requests:
  #  cpu: 100m
  #  memory: 2Gi  

nodeSelector: {}
  # kubernetes.io/hostname: minikube

tolerations: []

affinity: {}

securityContext: {}
  # runAsUser: 1000  